name: cifar100_imb001_stage2_ride
print_freq: 40
workers: 0
log_dir: 'logs'
model_dir: 'ckps'


# dataset & model setting
dataset: 'cifar10'
data_path: './data/cifar10'
num_classes: 10
imb_factor: 0.01
sampler:
  type: "weighted sampler" #'default' #
  weighted_sampler:
    type: "balance" #"balance"
  #dual_sample: 
  #  enable: False
  
backbone: 'resnet32'
classifier: 'ResClassifier'
resume: './current.pth.tar' #'model_best.pth.tar' #
head_class_idx:
  - 0
  - 3
med_class_idx:
  - 3
  - 7
tail_class_idx:
  - 7
  - 10
use_norm: True
num_experts: 3  

# distributed training
deterministic: True #False
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: None
dist_backend: 'nccl'
multiprocessing_distributed: False

#ResLT
loss:
  type: 'ResLoss'
  ResLT:
    beta: 0.5 
  #type: 'CrossEntropyLoss'  #'LDAMLoss' # 
  #LDAM:
  # reweight_epoch: 0

# Train
mode: 'stage2'
#smooth_head: 0.0 #0.4
#smooth_tail: 0.0 #0.1
shift_bn: True
lr: 0.1
lr_scheduler:
  type: 'cos'
  lr_factor: 0.5
batch_size: 512
weight_decay: 5e-4
num_epochs: 10
momentum: 0.9
mixup: False
alpha: null
H2T: -1.0
