name: cifar100_imb001_stage2_ce_h2t
print_freq: 40
workers: 0
log_dir: 'logs'
model_dir: 'ckps'


# dataset & model setting
dataset: 'cifar100'
data_path: './data/cifar100'
num_classes: 100
imb_factor: 0.01

sampler:
  type: "weighted sampler"
  weighted_sampler:
    type: "balance" #"reverse" # 
  dual_sample:
    enable: True
    type: 'long-tailed' #"reverse" # 'long-tailed'  


backbone: 'resnet32_fe'
resume: './cifar100_imb001_stage1.pth.tar'
head_class_idx:
  - 0
  - 36
med_class_idx:
  - 36
  - 71
tail_class_idx:
  - 71
  - 100
num_experts: 1  

# distributed training
deterministic: False
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: None 
dist_backend: 'nccl'
multiprocessing_distributed: False


# Train
mode: 'stage2'
shift_bn:  True #
lr_scheduler:
  type: 'cos'
  lr_factor: 0.2
lr: 0.1
batch_size: 128 #
weight_decay: 5e-4
num_epochs: 10
momentum: 0.9
mixup: False
alpha: null
H2T: 0.25
